-- CREATE USER 'newuser'@'localhost' IDENTIFIED BY 'password';
CREATE USER IF NOT EXISTS USCGuser@localhost IDENTIFIED BY 'USCG123';

DROP DATABASE IF EXISTS datalogDB2; 
SET default_storage_engine=InnoDB;
SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE DATABASE IF NOT EXISTS datalogDB2
    DEFAULT CHARACTER SET utf8mb4 
    DEFAULT COLLATE utf8mb4_unicode_ci;

GRANT CREATE, DROP, SELECT, INSERT, UPDATE, DELETE, FILE ON *.* TO 'USCGuser'@'localhost';
GRANT ALL PRIVILEGES ON `USCGuser`.* TO 'USCGuser'@'localhost';
GRANT ALL PRIVILEGES ON `datalogDB2`.* TO 'USCGuser'@'localhost';
FLUSH PRIVILEGES;



--CREATE TABLE datalogDB2.data (
--	CID INT NOT NULL AUTO_INCREMENT,
--	PRIMARY KEY (CID)
--	);	


--CREATE TABLE datalogDB2.device (
--	EID INT NOT NULL AUTO_INCREMENT,
--	TS DATETIME NOT NULL,
--	value0 FLOAT NOT NULL,
--	value1 FLOAT NOT NULL,
--	value2 FLOAT NOT NULL,
--	value3 FLOAT NOT NULL,
--	value4 FLOAT NOT NULL,
--	PRIMARY KEY (EID)
--	);	
--TS DATETIME,